### ISSUE TITLE
Interpreting process_debug.py info

### ISSUE THREAD

**Issue by nickvandewiele** [soravux/scoop#36]
Hi, 
I am trying to interpret the graphics produced by `bench/process_debug.py` after running my application with the `--debug` flag. It seems like a useful tool, but I want to interpret the results correctly.

I ran the app on a single machine with 4 CPUs and 4 workers. 

The `density_debug `plot shows that worker 0 has mostly a density of '2' whereas the other workers seem to have a density of '1'.
![density_debug](https://cloud.githubusercontent.com/assets/242147/13224879/81f2516c-d958-11e5-8eb4-897c22a9b834.png)

Does a density of `2` on a worker process mean that at a given time 2 tasks are competing for the same resources within a single process? Is it correct to deduce that in this case, worker 0 refers to the root worker that runs both root future as well as a future that consumes tasks?

Next question is about the `timeline_debug` plot:
![timeline_debug](https://cloud.githubusercontent.com/assets/242147/13225137/963c9be0-d959-11e5-856d-22a716501278.png)

As this plot also shows a metric per worker process as a function of time, I was wondering what the differences are between this plot, and density_debug plot? From the visualization of `timeline_debug` plot it seems that the workers are far less busy doing stuff than from the `density_debug `plot. Or should I interpret the blue bars differently here?

Any hints on this?
Thanks!

**Comment by soravux** [comment]
Hello,

You've found a feature that was not really well documented, as it served the developers understand how the balancing and inner workings of SCOOP behaved. As such, it was not very polished and sometimes rough around the edges.

A work density of 2 doesn't mean a competition, it only represents the full hierarchy (depth) of the processes being executed. On the root node, there are 2 tasks because the root task is being executed, and while it waits, it executes a task (2nd depth in the task hierarchy). Your interpretation is thus correct.

The blue bars in the timeline represents an event (task beginning / ending), and not the general usage. It was made to be complementary to the work density plot.

Hope it answers your questions!
