### ISSUE TITLE
scoopzmq  (127.0.0.1:52993) DEBUG   127.0.0.1:52993: Could not send result directly to peer 127.0.0.1:57612, routing through broker.

### ISSUE THREAD

**Issue by xinyanliang** [soravux/scoop#59]
scoopzmq  (127.0.0.1:52993) DEBUG   127.0.0.1:52993: Could not send result directly to peer 127.0.0.1:57612, routing through broker.

**Comment by soravux** [comment]
It happens when the result could not be sent directly to the peer, it's routing through the broker instead.

Have you checked your firewall configuration?
It can also happen on the first result sending, the connection can possible has not yet finished initializing. While it establishes the TCP connection, it routes the result through the broker.
