### ISSUE TITLE
[**Time Sensitive**] pyscoop.org domain expired

### ISSUE THREAD

**Issue by islamelnabarawy** [soravux/scoop#76]
The [http://pyscoop.org/](http://pyscoop.org/) URL currently redirects to a page saying the domain has expired and is up for renewal. It is currently in the `autoRenewPeriod` status.

@soravux Thank you for building this amazing library that has made my life as well as many others' lives much easier. I hope you can continue to maintain and contribute to this very useful piece of software. However, if you have decided to abandon this project and no longer intend to renew the domain name, please contact me _ASAP_. I would be happy to take over the domain name registration and the full-time maintenance of the project if needed. I have a vested interest in the continued survival of this project.

**Comment by soravux** [comment]
You can go ahead and register the domain if you'd like.

I believe the parallel programming ecosystem changed tremendously since the inception of SCOOP. When the project was started, the research community faced barren lands in terms of high-level parallel programming that supported common HPC environments. I believe SCOOP did a step in the right direction and lead the way in some aspects. However, this barren land is is no longer reality, as projects like celery, joblib, dask, and even vanilla multiprocessing or pytorch's version are well equipped to deal out-of-the-box or with minimum encumberance with common HPC environments. Furthermore, my research interests changed over the past few years and I doubt I will contribute much to SCOOP anymore.

It was a pleasure to help people and build something useful to me, my colleagues and the research community in general.

I believe GitHub issues are not ideal to talk about this. Contact me on the mailing list ( http://groups.google.com/group/scoop-users ) to continue this discussion.

**Comment by nathancarter** [comment]
It seems like this was not done, and now the website http://www.pyscoop.org/ is owned by a squatter, it seems, and sometimes navigating there tries to get me to install Chrome extensions (!?).  It's fine if no one wants to register the domain name, but then at the very least change the URL from the top of the GitHub project page so that it no longer lists pyscoop.org as the actual project homepage.

**Comment by soravux** [comment]
Thanks for reminding me of this URL, I just overlooked it earlier. It is now fixed.
